{{ define "booking-core.fullname" }}
  {{ if .Values.booking_core.fullnameOverride }}
    {{ .Values.booking_core.fullnameOverride | trunc 63 | trimSuffix "-" }}
  {{ else }}
    {{ $name := default .Chart.Name .Values.booking_core.nameOverride}}
    {{ if contains $name .Release.Name }}
      {{ .Release.Name | trunc 63 | trimSuffix "-" }}
    {{ else }}
      {{ printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
    {{ end }}
  {{ end }}
{{ end }}

{{- define "booking-core.labels" }}
helm.sh/chart: {{ include "booking-core.chart" . }}
  {{ include "booking-core.selectorLabels" . }}
  {{ if .Chart.AppVersion }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
  {{ end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{ define "booking-core.selectorLabels" }}
app.kubernetes.io/name: {{ include "booking-core.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{ end }}

{{ define "booking-core.chart" }}
  {{ printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{ end }}

{{ define "booking-core.name" }}
  {{- default .Chart.Name .Values.booking_core.nameOverride | trunc 63 | trimSuffix "-" }}
{{ end }}
