version: "3"
services:
  node:
    image: node:14.5.0-alpine3.12
    tty: true
    working_dir: /web
    environment:
      REACT_APP_API_BASE_URL: http://192.168.25.58:8447
    ports:
    - 3000:3000
    volumes:
    - ./:/web

  docker-registry:
    image: registry:2.7.0
    volumes:
    - ./htpasswd:/auth/htpasswd
    ports:
    - 8123:5000
    - 2378:2378
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: "/auth/htpasswd"

  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    depends_on:
      - docker-registry
    working_dir: ${PWD}
    ports:
    - 3001:3001
    - 3002:3002
    - 3003:3003
    volumes:
      - ./config.toml:/etc/gitlab-runner/config.toml
      - ${PWD}:${PWD}
      - /var/run/docker.sock:/var/run/docker.sock
