apiVersion: v1
kind: Namespace
metadata:
  name: ckad-1312
spec:
  finalizers:
    - kubernetes
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: 1312-pv
  namespace: ckad-1312
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: 1312-pvc
  namespace: ckad-1312
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: database
  name: database
  namespace: ckad-1312
spec:
  volumes:
    - name: pv-mount-point
      persistentVolumeClaim:
        claimName: 1312-pvc
  containers:
    - image: nginx
      name: database
      resources: {}
      volumeMounts:
        - mountPath: /webdata
          name: pv-mount-point
  dnsPolicy: ClusterFirst
  restartPolicy: Always
