apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: sidecar-pod
  name: sidecar-pod
  namespace: ckad-ns3
spec:
  volumes:
    - name: shared-data
      hostPath:
        path: data
  containers:
  - image: busybox
    name: main
    resources: {}
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /var/log
        name: shared-data
    command:
      - "sh"
      - "-c"
      - "while true; do sleep 5; date >> /var/log/date.log ; done"
  - image: busybox
    name: sidecar
    resources: {}
    imagePullPolicy: IfNotPresent
    volumeMounts:
      - mountPath: /var/log
        name: shared-data
    readinessProbe:
      initialDelaySeconds: 10
      exec:
        command:
          - "sh"
          - "-c"
          - "cat /var/log/date.log"
    command:
      - "sh"
      - "-c"
      - "sleep 10; tail -f /var/log/date.log;"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
